version: "3"
services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - iris
  kafka:
    image: docker.io/bitnami/kafka:3.3
    ports:
      - 9092:9092
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    networks:
      - iris
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8080:8080
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: iris-dev
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    networks:
      - iris
  mosquitto:
    image: eclipse-mosquitto:2.0.15
    ports:
      - 1883:1883
      - 9001:9001
    networks:
      - iris
    volumes:
      - ./volumes/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - 8001:8001
    volumes:
      - redisinsight:/db
    networks:
      - iris
volumes:
  redisinsight:
networks:
  iris:
    external: true
